#!/usr/bin/env bash
# Create a script to install and configure HAProxy on lb-01 server
# Configure HAProxy to send traffic to web-01 and web-02 servers
# Distribute requests using a roundrobin algorithm
# Make sure that HAProxy can be managed via an init script

# Install and configure HAproxy on my lb-01 server.
sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend BrianScotty_frontend
        bind *:80
        mode http
        default_backend BrianScotty_backend
backend BrianScotty_backend
        balance roundrobin
        server 424045-web-01 54.84.252.75:80 check
        server 424045-web-02 54.172.62.245:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# Testing the HAproxy configuration file
sudo haproxy -c -f /etc/haproxy/haproxy.cfg

# Restart the Nginx service
sudo service haproxy restart
